# services:
#   counter:
#     image: ${DOCKER_REGISTRY-}counter
#     build:
#       context: .
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - ASPNETCORE_URLS=http://+:5000
#     ports:
#       - "50010:50001"
#       - "5000:5000"

#   counter-dapr:
#     image: "daprio/daprd:1.7.4"
#     command: [ "./daprd", "-placement-host-address", "placement:50005", "-app-id", "counter", "-app-port", "5000" ]
#     depends_on:
#       - counter
#     network_mode: "service:counter"

#   placement:
#     image: "daprio/dapr:1.7.4"
#     command: ["./placement" ]
#     network_mode: "service:counter"

#   nettools:
#     image: qqbuby/net-tools:1.0
#     command:
#       - sleep
#       - 10h
#     network_mode: service:counter