version: '3.4'

services:
  mybackend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  myfrontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
